services:
  mongo:
    container_name: mongo
    image: mongo
    command: ["mongod", "--port", "857"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anchr
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - anchr_db_data:/data/db
      - ./scripts/mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-entrypoint.sh:ro
    ports:
      - 857:857
    networks:
      devops_bridge:
        ipv4_address: 172.18.0.2

  anchr:
    container_name: anchr
    image: anchr
    build:
      context: .
    ports:
      - "8080:${PORT}"
    volumes:
      - anchr_data:/app/data
    env_file: .env
    environment:
      - ANCHR_DB_HOST=mongo
      - ANCHR_DB_PORT=857
      - ANCHR_DB_NAME=admin
      - LISTEN_ADDR=0.0.0.0
    depends_on:
      - mongo
    networks:
      devops_bridge:
        ipv4_address: 172.18.0.3

volumes:
  anchr_data:
  anchr_db_data:

networks:
  devops_bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.18.0.0/29
        gateway: 172.18.0.1
